/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Qhi
 */
public class mainViewT extends javax.swing.JFrame {

    /**
     * Creates new form mainViewT
     */
    public mainViewT() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel2 = new javax.swing.JPanel();
        gambarLabel2 = new javax.swing.JLabel();
        userLabel2 = new javax.swing.JLabel();
        passwordLabel3 = new javax.swing.JLabel();
        titikduaLabel5 = new javax.swing.JLabel();
        titikduaLabel6 = new javax.swing.JLabel();
        userField2 = new javax.swing.JTextField();
        passwordField2 = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        Login2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtPemberitahuan = new javax.swing.JLabel();
        txtDisini = new javax.swing.JLabel();
        jPanelRegister = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jPasswordField7 = new javax.swing.JPasswordField();
        jTextField13 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cRegister6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        bodyView = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        homeView = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lokasiView = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        musikView = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        editProfileView = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        aboutView = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        logoutView = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        mainView = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lokasiPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        musikPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        editProfile = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        aboutPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi User");

        loginPanel2.setBackground(new java.awt.Color(153, 153, 153));
        loginPanel2.setPreferredSize(new java.awt.Dimension(550, 429));

        gambarLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-contacts-150 (1).png"))); // NOI18N

        userLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userLabel2.setText("User");

        passwordLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel3.setText("Password");

        titikduaLabel5.setText(":");

        titikduaLabel6.setText(":");

        userField2.setBackground(new java.awt.Color(153, 153, 153));
        userField2.setBorder(null);

        passwordField2.setBackground(new java.awt.Color(153, 153, 153));
        passwordField2.setBorder(null);

        Login2.setBackground(new java.awt.Color(153, 153, 153));
        Login2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("LOGIN");

        javax.swing.GroupLayout Login2Layout = new javax.swing.GroupLayout(Login2);
        Login2.setLayout(Login2Layout);
        Login2Layout.setHorizontalGroup(
            Login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Login2Layout.setVerticalGroup(
            Login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        txtPemberitahuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPemberitahuan.setText("Anda belum punya akun? registrasi");

        txtDisini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDisini.setText("disini");
        txtDisini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDisiniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanel2Layout = new javax.swing.GroupLayout(loginPanel2);
        loginPanel2.setLayout(loginPanel2Layout);
        loginPanel2Layout.setHorizontalGroup(
            loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(txtPemberitahuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDisini)
                .addGap(0, 155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel2Layout.createSequentialGroup()
                        .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLabel2)
                            .addComponent(passwordLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanel2Layout.createSequentialGroup()
                                .addComponent(titikduaLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(loginPanel2Layout.createSequentialGroup()
                                .addComponent(titikduaLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel2Layout.createSequentialGroup()
                        .addComponent(Login2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel2Layout.createSequentialGroup()
                        .addComponent(gambarLabel2)
                        .addGap(171, 171, 171))))
        );
        loginPanel2Layout.setVerticalGroup(
            loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(gambarLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel2)
                    .addComponent(titikduaLabel5)
                    .addComponent(userField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordLabel3)
                        .addComponent(titikduaLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Login2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(loginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPemberitahuan)
                    .addComponent(txtDisini))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanelRegister.setBackground(new java.awt.Color(153, 153, 153));
        jPanelRegister.setVisible(false);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel32.setText("Register");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Email");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Nama");

        jTextField14.setBackground(new java.awt.Color(153, 153, 153));
        jTextField14.setBorder(null);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Password");

        jPasswordField7.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordField7.setBorder(null);

        jTextField13.setBackground(new java.awt.Color(153, 153, 153));
        jTextField13.setBorder(null);

        cRegister6.setBackground(new java.awt.Color(204, 204, 204));
        cRegister6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cRegister6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cRegister6MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Create");

        javax.swing.GroupLayout cRegister6Layout = new javax.swing.GroupLayout(cRegister6);
        cRegister6.setLayout(cRegister6Layout);
        cRegister6Layout.setHorizontalGroup(
            cRegister6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cRegister6Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(39, 39, 39))
        );
        cRegister6Layout.setVerticalGroup(
            cRegister6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13)
                            .addComponent(jTextField14)
                            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34))
                                .addGap(0, 114, Short.MAX_VALUE))
                            .addComponent(jPasswordField7)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5))
                        .addGap(211, 211, 211))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(cRegister6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(43, 43, 43)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(cRegister6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        mainPanel.setPreferredSize(new java.awt.Dimension(552, 474));

        bodyView.setBackground(new java.awt.Color(153, 153, 153));

        menuPanel.setBackground(new java.awt.Color(153, 153, 153));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-32.png"))); // NOI18N
        homeView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeViewMouseClicked(evt);
            }
        });
        menuPanel.add(homeView, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 13, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel38.setText("Home");
        menuPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 51, -1, -1));

        lokasiView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-location-32.png"))); // NOI18N
        lokasiView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lokasiViewMouseClicked(evt);
            }
        });
        menuPanel.add(lokasiView, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 13, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel40.setText("Lokasi");
        menuPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 51, -1, -1));

        musikView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-musical-notes-32.png"))); // NOI18N
        musikView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musikViewMouseClicked(evt);
            }
        });
        menuPanel.add(musikView, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 13, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel42.setText("Musik");
        menuPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 51, -1, -1));

        editProfileView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-profile-32.png"))); // NOI18N
        editProfileView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileViewMouseClicked(evt);
            }
        });
        menuPanel.add(editProfileView, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel44.setText("Edit Profile");
        menuPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        aboutView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-more-info-32.png"))); // NOI18N
        aboutView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutViewMouseClicked(evt);
            }
        });
        menuPanel.add(aboutView, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel46.setText("About");
        menuPanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        logoutView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-shutdown-32.png"))); // NOI18N
        logoutView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutViewMouseClicked(evt);
            }
        });
        menuPanel.add(logoutView, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel48.setText("Logout");
        menuPanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        mainView.setBackground(new java.awt.Color(153, 153, 153));
        mainView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainView.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(153, 153, 255));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel49.setFont(new java.awt.Font("Tekton Pro Cond", 1, 48)); // NOI18N
        jLabel49.setText("Home");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel49)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel50.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel50.setText("Assalamu'alaikum");

        jLabel51.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel51.setText("Selamat berlatih netbeans disini");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel50))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel51)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50)
                .addGap(29, 29, 29)
                .addComponent(jLabel51)
                .addGap(0, 217, Short.MAX_VALUE))
        );

        mainView.add(homePanel, "card2");

        lokasiPanel.setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));

        jLabel52.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel52.setText("Lokasi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel53.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel53.setText("Silahkan cari lokasi anda");

        jTextField15.setBackground(new java.awt.Color(204, 204, 204));
        jTextField15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel54.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel54.setText("Cari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel54)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel54))
        );

        javax.swing.GroupLayout lokasiPanelLayout = new javax.swing.GroupLayout(lokasiPanel);
        lokasiPanel.setLayout(lokasiPanelLayout);
        lokasiPanelLayout.setHorizontalGroup(
            lokasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lokasiPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lokasiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lokasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lokasiPanelLayout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lokasiPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))))
        );
        lokasiPanelLayout.setVerticalGroup(
            lokasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lokasiPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addGap(20, 20, 20)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 180, Short.MAX_VALUE))
        );

        mainView.add(lokasiPanel, "card3");

        musikPanel.setBackground(new java.awt.Color(51, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel55.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel55.setText("Musik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel55)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addContainerGap())
        );

        jLabel56.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel56.setText("Maaf musik anda tidak tersedia !");

        javax.swing.GroupLayout musikPanelLayout = new javax.swing.GroupLayout(musikPanel);
        musikPanel.setLayout(musikPanelLayout);
        musikPanelLayout.setHorizontalGroup(
            musikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musikPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel56)
                .addGap(71, 71, 71))
        );
        musikPanelLayout.setVerticalGroup(
            musikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musikPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel56)
                .addGap(0, 140, Short.MAX_VALUE))
        );

        mainView.add(musikPanel, "card4");

        editProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 0));

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));

        jLabel57.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel57.setText("Edit Profile");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel57)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel58.setText("Nama");

        jLabel59.setText("Alamat");

        jLabel60.setText("Jenis Kelamin");

        jRadioButton1.setText("Laki-laki");

        jRadioButton2.setText("Perempuan");

        jTextField16.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel61.setText("Umur");

        jLabel62.setFont(new java.awt.Font("Tekton Pro Cond", 1, 24)); // NOI18N
        jLabel62.setText("Done");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel62)
                .addGap(29, 29, 29))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel62)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel58)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField16)
                            .addComponent(jTextField17, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel59)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel60))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30))
        );

        editProfile.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainView.add(editProfile, "card5");

        aboutPanel.setBackground(new java.awt.Color(44, 62, 80));

        jPanel9.setBackground(new java.awt.Color(41, 128, 185));

        jLabel63.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel63.setText("About");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel63)
                .addGap(225, 225, 225))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel63)
                .addContainerGap())
        );

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ganteng.png"))); // NOI18N

        jLabel65.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel65.setText("Mochamad Rifqi Hanapi");

        jLabel66.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel66.setText("IF-11");

        jLabel67.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel67.setText("JL.Mengger Girang 4 no 17A RT.08 RW.08");

        jLabel68.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel68.setText("Universitas Komputer Indonesia");

        jLabel69.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel69.setText("Developed");

        jLabel70.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel70.setText("Mochamad Rifqi Hanapi");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel64)
                        .addGap(57, 57, 57)
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel65)
                            .addComponent(jLabel67)
                            .addComponent(jLabel68)))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(jLabel69))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel65)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel66)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel67)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel68))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel64)))
                .addGap(38, 38, 38)
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel70)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        mainView.add(aboutPanel, "card6");

        javax.swing.GroupLayout bodyViewLayout = new javax.swing.GroupLayout(bodyView);
        bodyView.setLayout(bodyViewLayout);
        bodyViewLayout.setHorizontalGroup(
            bodyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bodyViewLayout.setVerticalGroup(
            bodyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainView, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void logoutViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutViewMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        lokasiPanel.setVisible(false);
        musikPanel.setVisible(false);
        editProfile.setVisible(false);
        aboutPanel.setVisible(false);
        loginPanel.setVisible(true);
        setExtendedState(JFrame.ICONIFIED);
        setExtendedState(JFrame.NORMAL);
    }//GEN-LAST:event_logoutViewMouseClicked

    private void aboutViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutViewMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        lokasiPanel.setVisible(false);
        musikPanel.setVisible(false);
        editProfile.setVisible(false);
        aboutPanel.setVisible(true);
    }//GEN-LAST:event_aboutViewMouseClicked

    private void editProfileViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileViewMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        lokasiPanel.setVisible(false);
        musikPanel.setVisible(false);
        editProfile.setVisible(true);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_editProfileViewMouseClicked

    private void musikViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musikViewMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        lokasiPanel.setVisible(false);
        musikPanel.setVisible(true);
        editProfile.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_musikViewMouseClicked

    private void lokasiViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lokasiViewMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        lokasiPanel.setVisible(true);
        musikPanel.setVisible(false);
        editProfile.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_lokasiViewMouseClicked

    private void homeViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeViewMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(true);
        lokasiPanel.setVisible(false);
        musikPanel.setVisible(false);
        editProfile.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_homeViewMouseClicked

    private void cRegister6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cRegister6MouseClicked
        // TODO add your handling code here:loginPanel.setVisible(true);
        loginPanel.setVisible(true);
        jPanelRegister.setVisible(false);
        mainPanel.setVisible(false);

    }//GEN-LAST:event_cRegister6MouseClicked

    private void txtDisiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDisiniMouseClicked
        loginPanel.setVisible(false);
        jPanelRegister.setVisible(true);
        mainPanel.setVisible(false);

    }//GEN-LAST:event_txtDisiniMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        loginPanel.setVisible(false);
        jPanelRegister.setVisible(false);
        mainPanel.setVisible(true);

    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainViewT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainViewT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainViewT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainViewT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainViewT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login2;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutView;
    private javax.swing.JPanel bodyView;
    private javax.swing.JPanel cRegister6;
    private javax.swing.JPanel editProfile;
    private javax.swing.JLabel editProfileView;
    private javax.swing.JLabel gambarLabel2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeView;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPasswordField jPasswordField7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JPanel loginPanel2;
    private javax.swing.JLabel logoutView;
    private javax.swing.JPanel lokasiPanel;
    private javax.swing.JLabel lokasiView;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainView;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel musikPanel;
    private javax.swing.JLabel musikView;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JLabel passwordLabel3;
    private javax.swing.JLabel titikduaLabel5;
    private javax.swing.JLabel titikduaLabel6;
    private javax.swing.JLabel txtDisini;
    private javax.swing.JLabel txtPemberitahuan;
    private javax.swing.JTextField userField2;
    private javax.swing.JLabel userLabel2;
    // End of variables declaration//GEN-END:variables
}
